<a href="https://colab.research.google.com/github/MoloZzz/nn/blob/main/sem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Імпортування модулів


In [1]:
import numpy as np
from sympy import *




#Дані:
###Приклад 1

In [2]:
A = Matrix([[1, -3], [8, 0]])
B = Matrix([[-1, 1], [0, 4]])
print('Приклад')
print(A,'-',2,'* X','=','3 *',B)
print('Перша дія')
print('3 *',B,'=',3*B)
print('Друга дія')
print('3 *',B,'-',A, '=',3 * B - A)
X = (3 * B - A)/-2
print('Результат')
print(X)
print('Перевірка')
print(A - 2 * X == 3 * B)


Приклад
Matrix([[1, -3], [8, 0]]) - 2 * X = 3 * Matrix([[-1, 1], [0, 4]])
Перша дія
3 * Matrix([[-1, 1], [0, 4]]) = Matrix([[-3, 3], [0, 12]])
Друга дія
3 * Matrix([[-1, 1], [0, 4]]) - Matrix([[1, -3], [8, 0]]) = Matrix([[-4, 6], [-8, 12]])
Результат
Matrix([[2, -3], [4, -6]])
Перевірка
True


###Приклад 2




In [3]:
A1 = np.array([[3,2,1],[2,3,1],[2,1,3]])
B1 = np.array([[3],[1],[4]])
C1 = np.array([[2],[-2],[0]])

from fractions import Fraction

print('Приклад(A * X = B + C)')
print(A1,'* Х = ',B1,"+",C1)
print('Перша дія(B + C)')
FirstAction1 = (B1 + C1)
print(FirstAction1)
print("Шукаємо детермінант, щоб знати чи існує обернена матриця, так як ділення матриць, це множення матриці на обернену")
print(np.linalg.det(A1) == 0)
print('Так як детермінант не 0, існує обернена матриця,знайдемо її')
print(A1)
print(np.linalg.inv(A1))
print(A1*np.linalg.inv(A1))
print("Числа дробові, не знаю як лишити дробом і не переводити в десяткові")


Приклад(A * X = B + C)
[[3 2 1]
 [2 3 1]
 [2 1 3]] * Х =  [[3]
 [1]
 [4]] + [[ 2]
 [-2]
 [ 0]]
Перша дія(B + C)
[[ 5]
 [-1]
 [ 4]]
Шукаємо детермінант, щоб знати чи існує обернена матриця, так як ділення матриць, це множення матриці на обернену
False
Так як детермінант не 0, існує обернена матриця,знайдемо її
[[3 2 1]
 [2 3 1]
 [2 1 3]]
[[ 0.66666667 -0.41666667 -0.08333333]
 [-0.33333333  0.58333333 -0.08333333]
 [-0.33333333  0.08333333  0.41666667]]
[[ 2.         -0.83333333 -0.08333333]
 [-0.66666667  1.75       -0.08333333]
 [-0.66666667  0.08333333  1.25      ]]
Числа дробові, не знаю як лишити дробом і не переводити в десяткові


###Приклад 3

In [7]:
A2 = np.array([[9,7,6],[1,1,2],[1,1,1]])
B2 = np.array([[2,0,-2],[18,12,9],[24,14,11]])
print("Приклад")
print("X * ",A1,' = ',B2)
print("Перша дія(знайти обернену до А)")
print(np.linalg.inv(A2))
print("Друга дія(Помножити на обернену)")
X2 = np.linalg.inv(A2)*B2
print(X2)
print("Перевірка(воно не працює, тому що обернену шукає не вірно,так як там дроби які неможливо перевести в десяткові)")
print(X2*A1==B2)

Приклад
X *  [[3 2 1]
 [2 3 1]
 [2 1 3]]  =  [[ 2  0 -2]
 [18 12  9]
 [24 14 11]]
Перша дія
[[ 0.5  0.5 -4. ]
 [-0.5 -1.5  6. ]
 [-0.   1.  -1. ]]
Друга дія
[[  1.   0.   8.]
 [ -9. -18.  54.]
 [ -0.  14. -11.]]
Перевірка
[[False  True False]
 [False False False]
 [False  True False]]


## Приклад 3


In [28]:
A31 = np.array([[2,1,3],[-1,4,2],[1,2,-2]])
B31 = np.array([[3,1,2],[4,-1,3]])
C31 = np.array([[0,-1,2],[-1,2,0]])

print("Приклад")
print("X * ",A31,'+2 ',B31," = 5 * ",C31)
print("Перша дія")
print(np.dot(2 ,B31))
print("Друга дія")
print(np.dot(5 ,C31))
print("Третя дія")
D31 = np.subtract(np.dot(5 ,C31), np.dot(2 ,B31))
print(D31)
print("Четверта дія")
print(np.linalg.inv(A31))
print("Результат")
inverse_A31 = np.linalg.inv(A31)
X31 = np.dot(D31, inverse_A31)
print(X31)
print("Перевірка - матриці не рівні,отже не можливо вирішити")
#print(X31 * A31 == 5 * C31 - 2*B31)

Приклад
X *  [[ 2  1  3]
 [-1  4  2]
 [ 1  2 -2]] +2  [[ 3  1  2]
 [ 4 -1  3]]  = 5 *  [[ 0 -1  2]
 [-1  2  0]]
Перша дія
[[ 6  2  4]
 [ 8 -2  6]]
Друга дія
[[ 0 -5 10]
 [-5 10  0]]
Третя дія
[[ -6  -7   6]
 [-13  12  -6]]
Четверта дія
[[ 0.28571429 -0.19047619  0.23809524]
 [ 0.          0.16666667  0.16666667]
 [ 0.14285714  0.07142857 -0.21428571]]
Результат
[[-0.85714286  0.4047619  -3.88095238]
 [-4.57142857  4.04761905  0.19047619]]
Перевірка - матриці не рівні,отже не можливо вирішити
